apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aks-keyvault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-aks-keyvault-app
  template:
    metadata:
      labels:
        app: my-aks-keyvault-app
        aadpodidentitybinding: my-identity-selector
        kubernetes.azure.com/pod-network: pn
        kubernetes.azure.com/pod-network-instance: pni
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: my-aks-keyvault-app
        image: isaac73/my-aks-keyvault-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        securityContext:
          privileged: true