apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth1defingresspbretp-dep
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: eth1defingresspbretp
  template:
    metadata:
      labels:
        app: eth1defingresspbretp
        azure.workload.identity/use: "true"
        kubernetes.azure.com/pod-network: pn
        kubernetes.azure.com/pod-network-instance: pni
    spec:
      serviceAccountName: mi-service-account
      nodeSelector:
        kubernetes.io/hostname: aks-work-36906996-vmss000002
      containers:
      - name: eth1defingresspbretp
        image: isaacacn.azurecr.io/pbrtest/my-aks-keyvault-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        command: ['sh', '-c', 'sh /scripts/configure-network.sh && /myapp']
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: network-scripts-eth1defingresspbretp
---
apiVersion: v1
kind: Service
metadata:
  name: eth1defingresspbretp-svc
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: eth1defingresspbretp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-scripts-eth1defingresspbretp
  namespace: default
data:
  configure-network.sh: |
    #!/bin/sh
  
    # Create eth0 routing table
    echo "200 eth0_table" >> /etc/iproute2/rt_tables

    # Make eth0 default in eth0_table
    ip route add default via 169.254.1.1 dev eth0 table eth0_table

    # connMark packets coming from eth0 as `1`
    iptables -t mangle -A PREROUTING -i eth0 -j CONNMARK --set-mark 1

    # Restore connMark to packet mark
    iptables -t mangle -A OUTPUT -j CONNMARK --restore-mark

    # Add a rule to lookup custom route table 200 for marked packets
    ip rule add fwmark 1 table 200

    echo "ip route show table eth0_table"
    ip route show table eth0_table
    echo "ip rule show"
    ip rule show
    echo "ip route show"
    ip route show