apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth0def-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth0def
  template:
    metadata:
      labels:
        app: eth0def
        azure.workload.identity/use: "true"
        kubernetes.azure.com/pod-network: pn
        kubernetes.azure.com/pod-network-instance: pni
    spec:
      serviceAccountName: mi-service-account
      nodeSelector:
        kubernetes.io/hostname: aks-standardd4s1-11101011-vmss000000
      containers:
      - name: eth0def
        image: isaac73/my-aks-keyvault-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: eth0def-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: eth0def