apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth1def-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth1def
  template:
    metadata:
      labels:
        app: eth1def
        azure.workload.identity/use: "true"
        kubernetes.azure.com/pod-network: pn
        kubernetes.azure.com/pod-network-instance: pni
    spec:
      initContainers:
      - name: init-myservice
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - echo "Starting initialization..."
          - echo "200 eth0_table" >> /etc/iproute2/rt_tables
          - ip route add default via 169.254.1.1 dev eth0 table eth0_table
          - ip rule add iif eth0 lookup eth0_table
      serviceAccountName: mi-service-account
      nodeSelector:
        kubernetes.io/hostname: aks-standardd4s1-11101011-vmss000000
      containers:
      - name: eth1def
        image: isaac73/my-aks-keyvault-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: eth1def-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: eth1def