apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name login.microsoftonline.com;

      location / {
        proxy_pass https://login.microsoftonline.com;
        proxy_ssl_server_name on;
        proxy_set_header Host $host;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nva-pod
  labels:
    app: nva
spec:
  containers:
  - name: nva-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
    volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nva-service
spec:
  type: LoadBalancer
  selector:
    app: nva
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
