apiVersion: v1
kind: Pod
metadata:
  name: nva-pod
  labels:
    app: nva
spec:
  containers:
  - name: nva-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: nva-service
spec:
  selector:
    app: nva
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nva-traffic
spec:
  podSelector:
    matchLabels:
      app: nva
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: my-aks-keyvault-app
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: my-aks-keyvault-app