
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: mi-service-account
      containers:
      - name: testapp
        image: isaac73/my-aks-keyvault-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: my-aks-keyvault-stsvc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: testapp